server:
  port: 8080
  servlet:
          context-path: /api/v1

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: 123

    data:
        redis:
           host: localhost
           port: 6379
           timeout: 60000
           database: 0

  servlet:
        multipart:
          max-file-size: 10MB
          max-request-size: 10MB
          enabled: true
          file-size-threshold: 5MB



  mail:
        host: smtp.gmail.com
        port: 587
        username: muslimyoldoshov41@gmail.com
        password: eaij jsek czwe jbvo
        properties:
          mail:
            smtp:
              auth: true
              starttls:
                enable: true
        default-encoding: UTF-8



  jpa:
      properties:
        hibernate:
          format_sql: true
          show_sql: true
      hibernate:
        ddl-auto: update





security:
  jwt:
    key: WC+qbHYl2B0o02421L+2UayDp2LtczY/3cSkAyErfTjmcEOXNtyjXq0un/SdY4cw


service:
  upload:
    dir: C:\Users\musli\AppData\Local\Temp\796d056e-c61c-4efc-808c-94be43cf8339_door-hub.zip.339\Hotel_Task\src\main\resources\image